# Generated by Django 3.2 on 2021-05-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fav_books_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='this is a blank description', max_length=255),
            preserve_default=False,
        ),
    ]
